#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 7/7/2016 10:05 AM
# Generated By: christnerw
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$button2 = New-Object System.Windows.Forms.Button
$button1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
##########################################################################################
#     Dowagic Copier B/W
##########################################################################################
function calldow{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Dowagiac\Dowagiac BW.ps1"
}
$button2_OnClick= ${function:calldow}
{
##########################################################################################
#     Dowagic Xerox Color
##########################################################################################
}
function calldowcolor{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Dowagiac\xerox.ps1"
}
$handler_button1_Click= ${function:calldowcolor}
{
###########################################################################################
#     End Of Line
##########################################################################################

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.BackgroundImage = [System.Drawing.Image]::FromFile('\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Main Installer\Images\Dowagic.jpg')
$form1.BackgroundImageLayout = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 284
$System_Drawing_Size.Width = 544
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Dowagiac"


$button2.DataBindings.DefaultDataSourceUpdateMode = 0
$button2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 346
$System_Drawing_Point.Y = 30
$button2.Location = $System_Drawing_Point
$button2.Name = "button2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 36
$System_Drawing_Size.Width = 167
$button2.Size = $System_Drawing_Size
$button2.TabIndex = 1
$button2.Text = "Dowagiac B/W"
$button2.UseVisualStyleBackColor = $True
$button2.add_Click($button2_OnClick)

$form1.Controls.Add($button2)


$button1.DataBindings.DefaultDataSourceUpdateMode = 0
$button1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 346
$System_Drawing_Point.Y = 92
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 36
$System_Drawing_Size.Width = 167
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 0
$button1.Text = "Dowagiac Color"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($handler_button1_Click)

$form1.Controls.Add($button1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
