#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 6/30/2016 12:29 PM
# Generated By: christnerw
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$button4 = New-Object System.Windows.Forms.Button
$button3 = New-Object System.Windows.Forms.Button
$button2 = New-Object System.Windows.Forms.Button
$button1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects
#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
####################################################################################
#           Bridge Academy Lab 1
####################################################################################
function calllab1{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Bridge Academy\BA Lab1.ps1"
}
$button3_OnClick= ${function:calllab1}
{
####################################################################################
#           Bridge Academy Copier B/W
####################################################################################
}
function callcopy{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Bridge Academy\BA Copier.ps1"
}
$button1_OnClick= ${function:callcopy}
{
####################################################################################
#           Bridge Academy Xerox Color
####################################################################################
}
function callxerox{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Bridge Academy\BA Xerox.ps1"
}

$button2_OnClick= ${function:callxerox}
{
####################################################################################
#           Bridge Academy Lab 2
####################################################################################
}
function calllab2{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Bridge Academy\BA Lab2.ps1"
}
$button4_OnClick= ${function:calllab2}
{
####################################################################################
#           End of Line
####################################################################################

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.BackgroundImage = [System.Drawing.Image]::FromFile('\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Main Installer\Images\Bridge Academy.jpg')
$form1.BackgroundImageLayout = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 336
$System_Drawing_Size.Width = 670
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Primal Form"


$button4.DataBindings.DefaultDataSourceUpdateMode = 0
$button4.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 547
$System_Drawing_Point.Y = 73
$button4.Location = $System_Drawing_Point
$button4.Name = "button4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 28
$System_Drawing_Size.Width = 101
$button4.Size = $System_Drawing_Size
$button4.TabIndex = 3
$button4.Text = "Lab 2"
$button4.UseVisualStyleBackColor = $True
$button4.add_Click($button4_OnClick)

$form1.Controls.Add($button4)


$button3.DataBindings.DefaultDataSourceUpdateMode = 0
$button3.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 459
$System_Drawing_Point.Y = 12
$button3.Location = $System_Drawing_Point
$button3.Name = "button3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 31
$System_Drawing_Size.Width = 101
$button3.Size = $System_Drawing_Size
$button3.TabIndex = 2
$button3.Text = "Lab 1"
$button3.UseVisualStyleBackColor = $True
$button3.add_Click($button3_OnClick)

$form1.Controls.Add($button3)


$button2.DataBindings.DefaultDataSourceUpdateMode = 0
$button2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 28
$System_Drawing_Point.Y = 73
$button2.Location = $System_Drawing_Point
$button2.Name = "button2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 28
$System_Drawing_Size.Width = 110
$button2.Size = $System_Drawing_Size
$button2.TabIndex = 1
$button2.Text = "Xerox Color"
$button2.UseVisualStyleBackColor = $True
$button2.add_Click($button2_OnClick)

$form1.Controls.Add($button2)


$button1.DataBindings.DefaultDataSourceUpdateMode = 0
$button1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 12
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 31
$System_Drawing_Size.Width = 110
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 0
$button1.Text = "Copier B/W"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($button1_OnClick)

$form1.Controls.Add($button1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
