#Generated Form Function
function GenerateForm {
########################################################################
# Generated On: 7/6/2016 9:20 AM
# Generated By: William Christner
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$button4 = New-Object System.Windows.Forms.Button
$button3 = New-Object System.Windows.Forms.Button
$button2 = New-Object System.Windows.Forms.Button
$button1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
###################################################################################
#       Dockside B/W
###################################################################################
function callDocksideBW{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\499\DocksideBW.ps1"
}
$button3_OnClick= ${function:callDocksideBW}
{
###################################################################################
#       Shoreline B/W
###################################################################################
}
function callShoreline{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\499\Shoreline.ps1"
}

$button1_OnClick= ${function:callShoreline}
{
###################################################################################
#       Shoreline Color
###################################################################################
}
function callShorelinecolor{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\499\Shorelinecolor.ps1"
}

$button2_OnClick= ${function:callShorelinecolor}
{
###################################################################################
#       Spinnaker
###################################################################################
}
function callspin{
."\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\499\Spinnaker.ps1"
}

$button4_OnClick= ${function:callspin}
{
##################################################################################
#        End Of Line
###################################################################################

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.BackgroundImage = [System.Drawing.Image]::FromFile('\\bh-miworks-srv2\PrintDrivers\Powershell Printer Install\Main Installer\Images\449.jpg')
$form1.BackgroundImageLayout = 3
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 281
$System_Drawing_Size.Width = 454
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.FormBorderStyle = 2
$form1.Name = "form1"
$form1.Text = "449"


$button4.DataBindings.DefaultDataSourceUpdateMode = 0
$button4.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 269
$System_Drawing_Point.Y = 158
$button4.Location = $System_Drawing_Point
$button4.Name = "button4"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 142
$button4.Size = $System_Drawing_Size
$button4.TabIndex = 3
$button4.Text = "Spinnaker B/W"
$button4.UseVisualStyleBackColor = $True
$button4.add_Click($button4_OnClick)

$form1.Controls.Add($button4)


$button3.DataBindings.DefaultDataSourceUpdateMode = 0
$button3.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 56
$System_Drawing_Point.Y = 158
$button3.Location = $System_Drawing_Point
$button3.Name = "button3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 147
$button3.Size = $System_Drawing_Size
$button3.TabIndex = 2
$button3.Text = "Dockside B/W"
$button3.UseVisualStyleBackColor = $True
$button3.add_Click($button3_OnClick)

$form1.Controls.Add($button3)


$button2.DataBindings.DefaultDataSourceUpdateMode = 0
$button2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 269
$System_Drawing_Point.Y = 54
$button2.Location = $System_Drawing_Point
$button2.Name = "button2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 142
$button2.Size = $System_Drawing_Size
$button2.TabIndex = 1
$button2.Text = "Shoreline Color"
$button2.UseVisualStyleBackColor = $True
$button2.add_Click($button2_OnClick)

$form1.Controls.Add($button2)


$button1.DataBindings.DefaultDataSourceUpdateMode = 0
$button1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 55
$System_Drawing_Point.Y = 54
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 148
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 0
$button1.Text = "Shoreline B/W"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($button1_OnClick)

$form1.Controls.Add($button1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
